version: '3.8'
services:
  db:
    image: mysql
    container_name: pcmdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pcm
    networks:
      - pcmnetwork
  api:
    image: python
    container_name: pcmapi

networks:
  pcmnetwork:
    driver: bridge
    name: pcm