version: '3.8'
services:
  db:
    image: mysql
    container_name: pcmdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pnb
    networks:
      - pnbnetwork
  api:
    image: python
    container_name: pcmapi

networks:
  pnbnetwork:
    driver: bridge
    name: pcm