version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: pcmdb
    ports:
      - "3306:3306"
    env_file:
      - db.env
    networks:
      - pcmnetwork
  api:
    image: python
    container_name: pcmapi

networks:
  pcmnetwork:
    driver: bridge
    name: pcm